name: MrMat Maturity Reporting Action
author: MrMat
description: A GitHub Action to report on project maturity

inputs:
    lint_report:
        description: Path to the lint report
        required: false

    unit_test_report:
        description: Path to the unit test report
        required: false

    coverage_report:
        description: Path to the coverage report
        required: false

outputs:
    report:
        description: The generated maturity report

runs:
    using: node24
    main: dist/index.js
